version: '3.8'

services:
  service:
    build: ./service
    image: bertt/testservice
    ports:
        - '81:80'
    depends_on: 
        - database
    environment:
        connect_db: "Data Source=database;Initial Catalog=master;User id=sa;Password=Yoyoyo800"
  database:
    image:  mcr.microsoft.com/mssql/server
    ports:
      - '1433:1433'
    volumes:
      - sqlvolume:/var/opt/mssql  
    environment:
        SA_PASSWORD: Yoyoyo800
        ACCEPT_EULA: Y
        MSSQL_PID: Express
volumes:
    sqlvolume: {}    